config:
  phases:
    - duration: 60
      arrivalRate: 30
  http:
    timeout: 29
scenarios:
  - flow:
      - post:
          url: "{{ url }}"
          json:
            name: "Big Unicorn"
            age: "13"
            type: "Beautiful"
            size: "196 cm"
